apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp-container
          image: yeraassyl/myapp:d69df6538aa823eaccfe08124759de7c11659866
          ports:
            - containerPort: 8080