name: Build and Deploy

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/myapp:${{ github.sha }}

      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Update git configuration
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'actions@github.com'
          git remote set-url origin git@github.com:${{ github.repository }}.git

      - name: Update Kubernetes manifests
        run: |
          sed -i "s|image: .*|image: ${{ secrets.DOCKER_USERNAME }}/myapp:${{ github.sha }}|" manifests/deployment.yaml
          git add manifests/deployment.yaml
          git commit -m "Update image to ${{ github.sha }}"
          git push origin HEAD:${{ github.ref }}